-- Generated: 2025-09-10 15:32:55
-- Purpose: Allergen Map

-- Allergen Group Mappings
CREATE TABLE IF NOT EXISTS allergen_map (
    id SERIAL PRIMARY KEY,
    allergen_group VARCHAR(50) NOT NULL,
    ingredient_token VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
);

INSERT INTO allergen_map (allergen_group, ingredient_token) VALUES
('chicken', 'chicken'),
('chicken', 'poultry'),
('chicken', 'poultry meal'),
('chicken', 'chicken meal'),
('chicken', 'chicken fat'),
('chicken', 'chicken liver'),
('chicken', 'chicken by-product'),
('chicken', 'hydrolyzed chicken'),
('beef', 'beef'),
('beef', 'bovine'),
('beef', 'beef meal'),
('beef', 'beef fat'),
('beef', 'beef liver'),
('beef', 'ox'),
('beef', 'veal'),
('fish_salmon', 'salmon'),
('fish_salmon', 'trout'),
('fish_salmon', 'whitefish'),
('fish_salmon', 'tuna'),
('fish_salmon', 'fish meal'),
('fish_salmon', 'fish oil'),
('fish_salmon', 'herring'),
('fish_salmon', 'mackerel'),
('fish_salmon', 'sardine'),
('fish_salmon', 'anchovy'),
('fish_salmon', 'cod'),
('fish_salmon', 'haddock'),
('fish_salmon', 'ocean fish'),
('fish_salmon', 'marine fish'),
('lamb', 'lamb'),
('lamb', 'ovine'),
('lamb', 'lamb meal'),
('lamb', 'mutton'),
('lamb', 'sheep'),
('turkey', 'turkey'),
('turkey', 'turkey meal'),
('turkey', 'turkey fat'),
('duck', 'duck'),
('duck', 'duck meal'),
('duck', 'duck fat'),
('pork', 'pork'),
('pork', 'porcine'),
('pork', 'bacon'),
('pork', 'ham'),
('pork', 'swine'),
('egg', 'egg'),
('egg', 'egg powder'),
('egg', 'dried egg'),
('egg', 'egg product'),
('dairy', 'milk'),
('dairy', 'whey'),
('dairy', 'casein'),
('dairy', 'cheese'),
('dairy', 'yogurt'),
('dairy', 'lactose'),
('dairy', 'dairy'),
('grain_gluten', 'wheat'),
('grain_gluten', 'barley'),
('grain_gluten', 'rye'),
('grain_gluten', 'oats'),
('grain_gluten', 'cereals'),
('grain_gluten', 'gluten'),
('grain_gluten', 'wheat flour'),
('grain_gluten', 'wheat germ'),
('grain_gluten', 'bran'),
('corn_maize', 'corn'),
('corn_maize', 'maize'),
('corn_maize', 'corn meal'),
('corn_maize', 'corn gluten'),
('corn_maize', 'corn starch'),
('soy', 'soya'),
('soy', 'soy'),
('soy', 'soy protein'),
('soy', 'soybean'),
('soy', 'soy meal'),
('pea_legume', 'pea'),
('pea_legume', 'lentil'),
('pea_legume', 'chickpea'),
('pea_legume', 'legume'),
('pea_legume', 'bean'),
('pea_legume', 'pulses'),
('potato', 'potato'),
('potato', 'sweet potato'),
('potato', 'potato starch'),
('potato', 'potato protein'),
('rice', 'rice'),
('rice', 'rice bran'),
('rice', 'brown rice'),
('rice', 'white rice'),
('rice', 'rice flour'),
('novel_protein', 'venison'),
('novel_protein', 'rabbit'),
('novel_protein', 'kangaroo'),
('novel_protein', 'insect'),
('novel_protein', 'buffalo'),
('novel_protein', 'goat'),
('novel_protein', 'ostrich'),
('novel_protein', 'wild boar'),
('novel_protein', 'bison'),
('novel_protein', 'alligator'),
('novel_protein', 'quail');